- name: Copy files to destination repository
  uses: lubu12/copy-files-to-repository@v1
  with:
    source-files: index.html styles.css files
    destination-username: Quantum404AK
    destination-repository: quantum404ak.github.io
    destination-branch: main
    destination-directory: projects/school_classwork_python
    commit-username: github-actions
    commit-email: ${{ github.actor }}@users.noreply.github.com
    commit-message: "Automated copy from ORIGIN_COMMIT"
  env:
    API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
